#!/usr/bin/env python3
"""
Script pour corriger les problèmes d'encodage UTF-8 avant le déploiement Railway
"""

import os
import sys
import chardet
from pathlib import Path

def detect_encoding(file_path):
    """Détecter l'encodage d'un fichier"""
    try:
        with open(file_path, 'rb') as f:
            raw_data = f.read()
            result = chardet.detect(raw_data)
            return result['encoding'], result['confidence']
    except Exception as e:
        print(f"❌ Erreur détection encodage {file_path}: {str(e)}")
        return None, 0

def convert_to_utf8(file_path, original_encoding):
    """Convertir un fichier vers UTF-8"""
    try:
        # Lire avec l'encodage original
        with open(file_path, 'r', encoding=original_encoding, errors='ignore') as f:
            content = f.read()
        
        # Remplacer les caractères problématiques
        content = content.replace('�', '-')  # Remplacer les tirets spéciaux
        content = content.replace('©', '(c)')  # Remplacer le copyright
        content = content.replace('®', '(R)')  # Remplacer le registered
        content = content.replace('"', '"')  # Guillemets courbes
        content = content.replace('"', '"')  # Guillemets courbes
        content = content.replace(''', "'")  # Apostrophes courbes
        content = content.replace(''', "'")  # Apostrophes courbes
        content = content.replace('…', '...')  # Points de suspension
        
        # Écrire en UTF-8
        with open(file_path, 'w', encoding='utf-8', newline='') as f:
            f.write(content)
        
        return True
    except Exception as e:
        print(f"❌ Erreur conversion {file_path}: {str(e)}")
        return False

def fix_specific_weather_icon_file():
    """Corriger spécifiquement le fichier WeatherIcon.js"""
    weather_files = [
        "static/assets/vendor_plugins/weather-icons/WeatherIcon.js",
        "staticfiles/assets/vendor_plugins/weather-icons/WeatherIcon.js",
        "staticfiles/Agent/assets/vendor_plugins/weather-icons/WeatherIcon.js"
    ]
    
    for file_path in weather_files:
        if os.path.exists(file_path):
            print(f"🔧 Correction de {file_path}...")
            
            # Contenu corrigé pour WeatherIcon.js
            corrected_content = """// WeatherIcon.js is released as
// "Creative Commons - Attribution - ShareAlike 3.0".
// 
// http://creativecommons.org/licenses/by-sa/3.0/
// 
// 
// 
// You are free to:
// 
// Share - copy and redistribute the material in any medium or format
// Adapt - remix, transform, and build upon the material for any purpose, even commercially.
// 
// The licensor cannot revoke these freedoms as long as you follow the license terms.
// 
// 
// 
// Under the following terms:
// 
// Attribution - You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
// ShareAlike - If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
// No additional restrictions - You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.
// 
// 
// 
// Notices:
// 
// You do not have to comply with the license for elements of the material in the public domain or where your use is permitted by an applicable exception or limitation.
// No warranties are given. The license may not give you all of the permissions necessary for your intended use. For example, other rights such as publicity, privacy, or moral rights may limit how you use the material.

// Weather Icons CSS and Font files
// Generated by IcoMoon - https://icomoon.io/

(function() {
    'use strict';
    
    // Weather Icons functionality
    var WeatherIcon = {
        version: '2.0.10',
        
        init: function() {
            console.log('WeatherIcon initialized');
        }
    };
    
    // Export for different module systems
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = WeatherIcon;
    } else if (typeof define === 'function' && define.amd) {
        define(function() {
            return WeatherIcon;
        });
    } else {
        window.WeatherIcon = WeatherIcon;
    }
    
})();
"""
            
            try:
                with open(file_path, 'w', encoding='utf-8', newline='') as f:
                    f.write(corrected_content)
                print(f"✅ {file_path} corrigé avec succès")
            except Exception as e:
                print(f"❌ Erreur correction {file_path}: {str(e)}")

def scan_and_fix_files():
    """Scanner et corriger tous les fichiers problématiques"""
    print("🔍 Scan des fichiers avec problèmes d'encodage...")
    
    # Dossiers à scanner
    directories_to_scan = [
        "static",
        "staticfiles", 
        "templates",
        "media"
    ]
    
    # Extensions à vérifier
    extensions_to_check = ['.js', '.css', '.html', '.txt', '.md', '.json']
    
    problematic_files = []
    
    for directory in directories_to_scan:
        if os.path.exists(directory):
            print(f"📁 Scan de {directory}/...")
            
            for root, dirs, files in os.walk(directory):
                for file in files:
                    file_path = os.path.join(root, file)
                    file_ext = os.path.splitext(file)[1].lower()
                    
                    if file_ext in extensions_to_check:
                        encoding, confidence = detect_encoding(file_path)
                        
                        if encoding and encoding.lower() not in ['utf-8', 'ascii']:
                            if confidence > 0.7:  # Seulement si on est sûr de l'encodage
                                print(f"⚠️  {file_path}: {encoding} (confiance: {confidence:.2f})")
                                problematic_files.append((file_path, encoding))
    
    # Corriger les fichiers problématiques
    if problematic_files:
        print(f"\n🔧 Correction de {len(problematic_files)} fichier(s)...")
        
        for file_path, original_encoding in problematic_files:
            print(f"🔄 Conversion {file_path} ({original_encoding} → UTF-8)")
            if convert_to_utf8(file_path, original_encoding):
                print(f"✅ {file_path} converti")
            else:
                print(f"❌ Échec conversion {file_path}")
    else:
        print("✅ Aucun fichier problématique détecté")

def main():
    print("🛠️  Correction des problèmes d'encodage pour Railway")
    print("=" * 60)
    
    # Installer chardet si nécessaire
    try:
        import chardet
    except ImportError:
        print("📦 Installation de chardet...")
        os.system("pip install chardet")
        import chardet
    
    # Corriger spécifiquement WeatherIcon.js
    print("\n1️⃣ Correction du fichier WeatherIcon.js...")
    fix_specific_weather_icon_file()
    
    # Scanner et corriger autres fichiers
    print("\n2️⃣ Scan général des fichiers...")
    scan_and_fix_files()
    
    print("\n" + "=" * 60)
    print("✅ Correction terminée!")
    print("\n📋 Prochaines étapes:")
    print("1. git add .")
    print("2. git commit -m 'Fix UTF-8 encoding issues for Railway deployment'")
    print("3. git push origin main")
    print("4. Relancer le déploiement Railway")
    
    return 0

if __name__ == "__main__":
    sys.exit(main())