# Generated by Django 5.2.7 on 2025-11-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adresse', '0002_initial'),
        ('Agent', '0001_initial'),
        ('Structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10)),
                ('nationalite', models.CharField(max_length=50)),
                ('type_client', models.CharField(choices=[('Physique', 'Physique'), ('Morale', 'Morale')], default='Homme', max_length=10)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('representant_legal', models.CharField(blank=True, default='Aucun', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients_photos/')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_adresse', to='Adresse.adresse')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Structure.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reference_dossier', models.CharField(help_text='Référence unique attribuée par le cabinet (ex: CABINET/ANNEE/CLIENT_ID)', max_length=50, unique=True, verbose_name='N° de Dossier')),
                ('titre', models.CharField(max_length=200, verbose_name='Objet/Titre du Dossier')),
                ('mode_honoraire', models.CharField(choices=[('Forfait', 'Forfaitaire'), ('Normal', 'Normalisé')], default='Normal', max_length=10, null=True)),
                ('forfait_defini', models.BooleanField(default=False)),
                ('mode_defini', models.BooleanField(default=False)),
                ('statut_dossier', models.CharField(choices=[('Ouvert', 'Ouvert'), ('En Cours', 'En Cours'), ('Suspendu', 'Suspendu'), ('Clôturé', 'Clôturé')], default='Ouvert', max_length=20, verbose_name='Statut du Dossier')),
                ('partie_adverse_nom', models.CharField(blank=True, max_length=200, null=True)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_cloture', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gagner ou perdu')),
                ('montant_dollars_enreg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_fc_enreg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taux_enreg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='Structure.cabinet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossiers_client', to='Dossier.client', verbose_name='Client associé')),
                ('juridiction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_jridiction', to='Structure.juridiction')),
            ],
            options={
                'verbose_name': 'Dossier Client',
                'verbose_name_plural': 'Dossiers Clients',
            },
        ),
        migrations.CreateModel(
            name='DeclarationDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu de la Déclaration')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent.agent', verbose_name='Agent ayant ajouté la déclaration')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations', to='Dossier.dossier', verbose_name='Dossier associé')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ActiviteHeure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activite', models.DateField(verbose_name="Date de l'activité")),
                ('duree_heures', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Durée (en heures, ex: 1.50)')),
                ('description', models.TextField(verbose_name="Description de l'activité (pour la facture)")),
                ('facturee', models.BooleanField(default=False)),
                ('avocat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent.agent', verbose_name='Avocat/Agent')),
                ('cabinet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_activite', to='Structure.cabinet')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_temps', to='Dossier.dossier', verbose_name='Dossier concerné')),
            ],
        ),
        migrations.CreateModel(
            name='PieceDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Exemple : Contrat, Jugement, Assignation, Preuve, etc.', max_length=150)),
                ('fichier', models.FileField(upload_to='pieces_dossier/', verbose_name='Fichier à téléverser')),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('format_fichier', models.CharField(default='document', max_length=150)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_ajoutees', to='Agent.agent', verbose_name='Ajouté par')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_dossier', to='Dossier.dossier', verbose_name='Dossier concerné')),
            ],
            options={
                'verbose_name': 'Pièce du dossier',
                'verbose_name_plural': 'Pièces du dossier',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='SecteurFoncier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cabinet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_secteur', to='Structure.cabinet')),
                ('communes', models.ManyToManyField(blank=True, related_name='secteurs', to='Adresse.commune')),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='secteur_foncier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_secteur', to='Dossier.secteurfoncier', verbose_name='Secteur Foncier'),
        ),
        migrations.CreateModel(
            name='TarifActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_dollars', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de l’activité (Fc)')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_activites', to='Structure.activite')),
                ('cabinet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_Tarifactivite', to='Structure.cabinet')),
            ],
            options={
                'verbose_name': 'Tarif par Activité',
                'verbose_name_plural': 'Tarifs par Activité',
            },
        ),
        migrations.CreateModel(
            name='ReductionTarifForfaitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_reduit_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_reduit_fc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions_forfaitaires', to='Dossier.dossier')),
                ('activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.tarifactivite')),
            ],
        ),
        migrations.CreateModel(
            name='TarifHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_fc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant par heure')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('montant_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant Forfaitaire de Base')),
                ('taux_jour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cabinet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarif_cabinet', to='Structure.cabinet')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_horaires_secteurs', to='Dossier.secteurfoncier')),
            ],
            options={
                'verbose_name': 'Tarif Horaire',
                'verbose_name_plural': 'Tarifs Horaires',
            },
        ),
        migrations.AddField(
            model_name='tarifactivite',
            name='tarif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_tarif', to='Dossier.tarifhoraire'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='tarif_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dossier.tarifhoraire', verbose_name='Référence Tarifaire'),
        ),
        migrations.CreateModel(
            name='type_dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=100)),
                ('date_ajouter', models.DateField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_type_dossier', to='Structure.cabinet')),
            ],
        ),
        migrations.AddField(
            model_name='tarifhoraire',
            name='type_dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_horaires_dossier', to='Dossier.type_dossier'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='type_affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_type', to='Dossier.type_dossier'),
        ),
        migrations.CreateModel(
            name='TypePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_type', models.CharField(max_length=150)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Structure.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='AvocatDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Principal', 'Avocat Principal'), ('Support', 'Avocat de Support'), ('Partenaire', 'Avocat Partenaire Externe')], default='Support', max_length=20, verbose_name='Rôle dans le dossier')),
                ('date_assignation', models.DateField(auto_now_add=True, verbose_name="Date d'assignation")),
                ('avocat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent.agent')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.dossier')),
            ],
            options={
                'verbose_name': 'Assignation Avocat-Dossier',
                'unique_together': {('dossier', 'avocat')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tarifactivite',
            unique_together={('tarif', 'activite')},
        ),
        migrations.AlterUniqueTogether(
            name='tarifhoraire',
            unique_together={('type_dossier', 'secteur')},
        ),
    ]
