# Generated by Django 5.2.7 on 2025-12-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
