# Generated by Django 5.2.7 on 2025-12-17 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_initial'),
        ('Dossier', '0002_dossier_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationdossier',
            name='ecrit_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Agent.agent', verbose_name='Agent ayant ajouté la déclaration'),
        ),
        migrations.AlterField(
            model_name='declarationdossier',
            name='auteur',
            field=models.CharField(default='', max_length=100),
        ),
    ]
