# Generated by Django 5.2.7 on 2025-12-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0003_declarationdossier_ecrit_par_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='observation',
            field=models.TextField(default='', verbose_name="Dernier mot de l'avocat"),
        ),
    ]
