# Generated by Django 5.2.7 on 2025-12-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0004_dossier_observation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='secteurfoncier',
            options={'verbose_name': 'Secteur Foncier', 'verbose_name_plural': 'Secteurs Fonciers'},
        ),
        migrations.AlterModelOptions(
            name='type_dossier',
            options={'verbose_name': 'Type de dossier', 'verbose_name_plural': 'Types de dossiers'},
        ),
        migrations.AlterModelTable(
            name='activiteheure',
            table='dossier_activiteheure',
        ),
        migrations.AlterModelTable(
            name='avocatdossier',
            table='dossier_avocatdossier',
        ),
        migrations.AlterModelTable(
            name='client',
            table='dossier_client',
        ),
        migrations.AlterModelTable(
            name='declarationdossier',
            table='dossier_declarationdossier',
        ),
        migrations.AlterModelTable(
            name='dossier',
            table='dossier_dossier',
        ),
        migrations.AlterModelTable(
            name='piecedossier',
            table='dossier_piecedossier',
        ),
        migrations.AlterModelTable(
            name='reductiontarifforfaitaire',
            table='dossier_reductiontarifforfaitaire',
        ),
        migrations.AlterModelTable(
            name='secteurfoncier',
            table='dossier_secteurfoncier',
        ),
        migrations.AlterModelTable(
            name='tarifactivite',
            table='dossier_tarifactivite',
        ),
        migrations.AlterModelTable(
            name='tarifhoraire',
            table='dossier_tarifhoraire',
        ),
        migrations.AlterModelTable(
            name='type_dossier',
            table='dossier_type_dossier',
        ),
        migrations.AlterModelTable(
            name='typepiece',
            table='dossier_typepiece',
        ),
    ]
