# Generated by Django 5.2.7 on 2025-12-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compteutilisateur',
            options={'verbose_name': 'Compte Utilisateur', 'verbose_name_plural': 'Comptes Utilisateurs'},
        ),
        migrations.AlterModelTable(
            name='compteutilisateur',
            table='authentification_compteutilisateur',
        ),
    ]
