# Generated by Django 5.2.7 on 2025-11-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agent', '0001_initial'),
        ('Dossier', '0001_initial'),
        ('Structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personne_qui_paie', models.CharField(blank=True, max_length=200, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(choices=[('USD', 'USD'), ('FC', 'FC')], max_length=10)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('type_paiement', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('taux', models.TextField(blank=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='paiements/')),
                ('agent', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_agent', to='Agent.agent')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Structure.cabinet')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_client', to='Dossier.client')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Dossier.dossier')),
            ],
        ),
    ]
