# Generated by Django 5.2.7 on 2025-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='montant',
            new_name='montant_payer_dollars',
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_payer_fc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_reste_dollars',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='paiement',
            name='montant_reste_fc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
