# Generated by Django 5.2.7 on 2025-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_rename_montant_paiement_montant_payer_dollars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
