# Generated by Django 5.2.7 on 2025-12-06 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0003_paiement_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='reference',
        ),
    ]
