# Generated by Django 5.2.7 on 2025-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0004_remove_paiement_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='motif',
            field=models.CharField(default='Paiement du client', max_length=100),
        ),
    ]
