# Generated by Django 5.2.7 on 2025-12-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0005_paiement_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='type_operation',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], default='ENTREE', max_length=20),
        ),
    ]
