# Generated by Django 5.2.7 on 2025-12-11 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0002_dossier_reference'),
        ('paiement', '0006_paiement_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_client', to='Dossier.client'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='dossier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='Dossier.dossier'),
        ),
    ]
