# Generated by Django 5.2.7 on 2025-12-11 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0007_alter_paiement_client_alter_paiement_dossier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='devise',
            new_name='deviseS',
        ),
    ]
