# Generated by Django 5.2.7 on 2025-12-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0008_rename_devise_paiement_devises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paiement',
            old_name='deviseS',
            new_name='devise',
        ),
    ]
