# Generated by Django 5.2.7 on 2025-12-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0008_alter_banque_options_alter_banque_nom_banque_and_more'),
        ('paiement', '0009_rename_devises_paiement_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='banque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banque_paye', to='Structure.banque'),
        ),
    ]
