# Generated by Django 5.2.7 on 2025-11-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adresse', '0002_initial'),
        ('Structure', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_identification', models.CharField(help_text='Numéro d’identification de l’avocat ou de l’agent', max_length=50, unique=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10)),
                ('poste', models.CharField(blank=True, choices=[('Administrateur', 'Administrateur'), ('Avocat', 'Avocat'), ('Secretaire', 'Secrétaire')], max_length=100, null=True)),
                ('annee_experience', models.CharField(blank=True, default=0, max_length=5)),
                ('a_propos', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, upload_to='PhotoAgent/')),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_adresse', to='Adresse.adresse')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_agent', to='Structure.cabinet')),
                ('groupe_attribue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupe_agents', to='auth.group')),
                ('specialite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='Structure.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_piece', models.CharField(blank=True, max_length=50, null=True)),
                ('fichier', models.FileField(upload_to='pieces_justificatives/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_agent', to='Agent.agent')),
            ],
        ),
    ]
