# Generated by Django 5.2.7 on 2025-11-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agent', '0001_initial'),
        ('Dossier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecejustificative',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_client', to='Dossier.client'),
        ),
        migrations.AddField(
            model_name='piecejustificative',
            name='type_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Type_pieces_Justificative', to='Dossier.typepiece'),
        ),
    ]
