# Generated by Django 5.2.7 on 2025-12-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='piecejustificative',
            options={'verbose_name': 'Pièce justificative', 'verbose_name_plural': 'Pièces justificatives'},
        ),
        migrations.AlterModelTable(
            name='agent',
            table='agent_agent',
        ),
        migrations.AlterModelTable(
            name='piecejustificative',
            table='agent_piecejustificative',
        ),
    ]
