# Generated by Django 5.2.7 on 2025-12-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0005_simple_activity_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='SimpleActivityLog',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
