# Generated by Django 5.2.7 on 2025-11-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adresse', '0001_initial'),
        ('Structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='Structure.cabinet'),
        ),
        migrations.AddField(
            model_name='ville',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Structure.cabinet'),
        ),
    ]
