# Generated by Django 5.2.7 on 2025-12-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adresse', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adresse',
            options={'verbose_name': 'Adresse', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name': 'Commune', 'verbose_name_plural': 'Communes'},
        ),
        migrations.AlterModelOptions(
            name='ville',
            options={'verbose_name': 'Ville', 'verbose_name_plural': 'Villes'},
        ),
        migrations.AlterModelTable(
            name='adresse',
            table='adresse_adresse',
        ),
        migrations.AlterModelTable(
            name='commune',
            table='adresse_commune',
        ),
        migrations.AlterModelTable(
            name='ville',
            table='adresse_ville',
        ),
    ]
