# Generated by Django 5.2.7 on 2025-11-27 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adresse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forme_juridiques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=False, max_length=200)),
                ('numero_identification', models.CharField(blank=True, default=False, max_length=50)),
                ('telephone_secondaire', models.CharField(blank=True, default=False, max_length=50)),
                ('telephone', models.CharField(blank=True, default=False, max_length=50)),
                ('num_id_fiscal', models.CharField(blank=True, default=False, max_length=50)),
                ('date_creations', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, default=False, max_length=100)),
                ('reference', models.CharField(blank=True, default=False, max_length=500)),
                ('site_web', models.CharField(blank=True, default=False, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='LogoCabinet/')),
                ('adresse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_adresse', to='Adresse.adresse')),
                ('forme_juridique', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Structure.forme_juridiques')),
            ],
        ),
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_activite', models.CharField(max_length=200)),
                ('date_activite', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets_Activites', to='Structure.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Juridiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Juridiction_cabinet', to='Structure.cabinet')),
                ('lieu', models.ForeignKey(default='Aucune adresse', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Adresse.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_ajouter', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_specialite', to='Structure.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='PosteAvocat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_poste', models.CharField(max_length=100, unique=True)),
                ('date_ajouter', models.DateTimeField(auto_now_add=True, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinets_poste', to='Structure.cabinet')),
            ],
            options={
                'verbose_name': "Poste d'avocat",
                'verbose_name_plural': "Postes d'avocats",
                'unique_together': {('nom_poste', 'cabinet')},
            },
        ),
    ]
