# Generated by Django 5.2.7 on 2025-11-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='nom_fondateur',
            field=models.CharField(blank=True, default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='reference',
            field=models.TextField(blank=True, default=False),
        ),
    ]
