# Generated by Django 5.2.7 on 2025-11-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0002_cabinet_nom_fondateur_alter_cabinet_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='date_creations',
            field=models.DateField(blank=True, null=True),
        ),
    ]
