# Generated by Django 5.2.7 on 2025-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0003_alter_cabinet_date_creations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
