# Generated by Django 5.2.7 on 2025-12-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0004_alter_cabinet_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=100, unique=True)),
                ('date_ajouter', models.DateTimeField(auto_now_add=True, null=True)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_cabinet', to='Structure.cabinet')),
            ],
            options={
                'verbose_name': 'Service cabinet',
                'verbose_name_plural': 'Services cabinet',
                'unique_together': {('nom_service', 'cabinet')},
            },
        ),
    ]
