# Generated by Django 5.2.7 on 2025-12-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0005_servicecabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecabinet',
            name='nom_service',
            field=models.CharField(max_length=100),
        ),
    ]
