# Generated by Django 5.2.7 on 2025-12-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0006_alter_servicecabinet_nom_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_banque', models.CharField(max_length=255, unique=True)),
                ('numero_compte', models.CharField(max_length=255)),
                ('date_ajouter', models.DateTimeField(auto_now_add=True)),
                ('cabinet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Banque_cabinet', to='Structure.cabinet')),
            ],
        ),
    ]
