# Generated by Django 5.2.7 on 2025-12-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0007_banque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banque',
            options={'verbose_name': 'Banque cabinet', 'verbose_name_plural': 'Banques cabinet'},
        ),
        migrations.AlterField(
            model_name='banque',
            name='nom_banque',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='banque',
            unique_together={('nom_banque', 'cabinet')},
        ),
    ]
