# Generated by Django 5.2.7 on 2025-12-28 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Structure', '0008_alter_banque_options_alter_banque_nom_banque_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activite',
            options={'verbose_name': 'Activité', 'verbose_name_plural': 'Activités'},
        ),
        migrations.AlterModelOptions(
            name='cabinet',
            options={'verbose_name': 'Cabinet', 'verbose_name_plural': 'Cabinets'},
        ),
        migrations.AlterModelOptions(
            name='forme_juridiques',
            options={'verbose_name': 'Forme juridique', 'verbose_name_plural': 'Formes juridiques'},
        ),
        migrations.AlterModelOptions(
            name='juridiction',
            options={'verbose_name': 'Juridiction', 'verbose_name_plural': 'Juridictions'},
        ),
        migrations.AlterModelOptions(
            name='specialite',
            options={'verbose_name': 'Spécialité', 'verbose_name_plural': 'Spécialités'},
        ),
        migrations.AlterModelTable(
            name='activite',
            table='structure_activite',
        ),
        migrations.AlterModelTable(
            name='banque',
            table='structure_banque',
        ),
        migrations.AlterModelTable(
            name='cabinet',
            table='structure_cabinet',
        ),
        migrations.AlterModelTable(
            name='forme_juridiques',
            table='structure_forme_juridiques',
        ),
        migrations.AlterModelTable(
            name='juridiction',
            table='structure_juridiction',
        ),
        migrations.AlterModelTable(
            name='posteavocat',
            table='structure_posteavocat',
        ),
        migrations.AlterModelTable(
            name='servicecabinet',
            table='structure_servicecabinet',
        ),
        migrations.AlterModelTable(
            name='specialite',
            table='structure_specialite',
        ),
    ]
